# Generated by Django 6.1.1 on 2026-09-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('UNDEFINED', 'UNDEFINED'), ('BSIT', 'BSIT'), ('BSA', 'BSA'), ('BSAIS', 'BSAIS'), ('BSE', 'BSE'), ('BSSW', 'BSSW'), ('BSPA', 'BSPA'), ('DHRS', 'DHRS'), ('BTVTED', 'BTVTED'), ('ABELS', 'ABELS')], default='UNDEFINED')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('UNDEFINED', 'UNDEFINED')], default='UNDEFINED')),
            ],
        ),
    ]
